parameters:
    mfw_qr_generator.class: MadForWebs\QRGeneratorBundle\Lib\Generator

services:
   mfw_qr_generator:
       class: %mfw_qr_generator.class%
       arguments: ["@doctrine.orm.entity_manager", "@router"]